/**
 * System category label mapping.
 *
 * System categories are seeded into the DB with Chinese names (their `name`
 * column is the storage and matching identity — category creation, resolution
 * and template checks compare against these names). Records link to categories
 * by `categoryId`, so the stored name never changes for existing data.
 *
 * For display we map a known system category name to an i18n key so the UI can
 * render localized labels while the DB value stays stable. Unknown names
 * (user-created categories) are returned as-is.
 */
import { translate } from "@/lib/i18n-core";
import { FIXED_ASSET_EXPENSE_CATEGORY_NAME } from "@/lib/fixed-asset";

type TFunc = (key: string, params?: Record<string, string | number>) => string;

const SYSTEM_CATEGORY_LABEL_KEYS: Record<string, string> = {
"爱车养车": "systemCategory.carCare",
  "办公用品": "systemCategory.officeSupplies",
  "保健品": "systemCategory.healthSupplements",
  "保险": "systemCategory.insurance",
  "保险回款": "systemCategory.insuranceReturn",
  "保险支出": "systemCategory.insuranceExpense",
  "保养维修": "systemCategory.maintenanceRepair",
  "报销": "systemCategory.reimbursement",
  "餐饮费": "systemCategory.dining",
  "餐饮美食": "systemCategory.foodDining",
  "差旅": "systemCategory.businessTravel",
  "车险车税": "systemCategory.carInsuranceTax",
  "充电": "systemCategory.evCharging",
  "充值缴费": "systemCategory.topUpBills",
  "宠物": "systemCategory.pets",
  "出借": "systemCategory.lendOut",
  "存款存入": "systemCategory.depositIn",
  "存款利息": "systemCategory.depositInterest",
  "存款取出": "systemCategory.depositOut",
  "存款手续费": "systemCategory.depositFee",
  "存款投资": "systemCategory.depositInvestment",
  "打车": "systemCategory.rideHailing",
  "贷款": "systemCategory.loan",
  "贷款本金": "systemCategory.loanPrincipal",
  "贷款还款": "systemCategory.loanRepayment",
  "贷款利息": "systemCategory.loanInterest",
  "贷款手续费": "systemCategory.loanFee",
  "电费": "systemCategory.electricity",
  "电影演出": "systemCategory.moviesShows",
  "儿童保险": "systemCategory.childrenInsurance",
  "儿童医疗": "systemCategory.childrenMedical",
  "房产出售": "systemCategory.propertySale",
  "房产购入": "systemCategory.propertyPurchase",
  "房产投资": "systemCategory.propertyInvestment",
  "房贷": "systemCategory.mortgage",
  "房租": "systemCategory.rent",
  [FIXED_ASSET_EXPENSE_CATEGORY_NAME]: "systemCategory.fixedAsset",
  "分红再投资": "systemCategory.dividendReinvest",
  "服饰鞋包": "systemCategory.apparelShoesBags",
  "服饰装扮": "systemCategory.clothingFashion",
  "服饰装饰": "systemCategory.apparelAccessories",
  "服务收入": "systemCategory.serviceIncome",
  "福利补助": "systemCategory.benefitsAllowances",
  "副业收入": "systemCategory.sideIncome",
  "工资": "systemCategory.salary",
  "工作经营": "systemCategory.workBusiness",
  "工作收入": "systemCategory.employmentIncome",
  "公共服务": "systemCategory.publicServices",
  "公积金": "systemCategory.housingFund",
  "公交地铁": "systemCategory.busMetro",
  "公司差旅费": "systemCategory.companyTravelAdvance",
  "公司代付": "systemCategory.companyPaymentAdvance",
  "公司代购费": "systemCategory.companyPurchaseAdvance",
  "公司其他代付": "systemCategory.companyOtherAdvance",
  "公益捐赠": "systemCategory.charityDonation",
  "供暖费": "systemCategory.heating",
  "股票分红": "systemCategory.stockDividend",
  "股票亏损": "systemCategory.stockLoss",
  "股票买入": "systemCategory.stockBuy",
  "股票卖出": "systemCategory.stockSell",
  "股票收益": "systemCategory.stockProfit",
  "股票税费": "systemCategory.stockFee",
  "股票投资": "systemCategory.stockInvestment",
  "股息分红": "systemCategory.dividend",
  "挂号门诊": "systemCategory.clinicVisits",
  "贵金属买入": "systemCategory.metalBuy",
  "贵金属卖出": "systemCategory.metalSell",
  "贵金属投资": "systemCategory.metalInvestment",
  "过路费": "systemCategory.tolls",
  "还款": "systemCategory.repayment",
  "红包": "systemCategory.redPacket",
  "红包礼金": "systemCategory.giftMoney",
  "互助保障": "systemCategory.mutualAid",
  "会员订阅": "systemCategory.membershipSubscriptions",
  "婚丧嫁娶": "systemCategory.weddingsFunerals",
  "火车高铁": "systemCategory.trainsHighSpeedRail",
  "机票": "systemCategory.flights",
  "基金定投": "systemCategory.fundRegularInvest",
  "基金亏损": "systemCategory.fundLoss",
  "基金买入": "systemCategory.fundBuy",
  "基金收益": "systemCategory.fundProfit",
  "基金赎回": "systemCategory.fundRedeem",
  "基金投资": "systemCategory.fundInvestment",
  "绩效": "systemCategory.performanceBonus",
  "加班费": "systemCategory.overtimePay",
  "加油": "systemCategory.fuel",
  "家居家装": "systemCategory.homeFurnishing",
  "家居用品": "systemCategory.homeGoods",
  "家居装饰": "systemCategory.homeDecor",
  "家具家电": "systemCategory.furnitureAppliances",
  "家人转入": "systemCategory.fromFamily",
  "家庭补贴": "systemCategory.familyAllowance",
  "家庭往来": "systemCategory.familyTransfers",
  "家用电器": "systemCategory.homeAppliances",
  "兼职收入": "systemCategory.partTimeIncome",
  "健身运动": "systemCategory.fitnessSports",
  "奖金": "systemCategory.bonus",
  "交通出行": "systemCategory.transportation",
  "交通费": "systemCategory.transportExpenses",
  "教育成长": "systemCategory.educationGrowth",
  "教育培训": "systemCategory.educationTraining",
  "节日礼物": "systemCategory.holidayGifts",
  "借款收回": "systemCategory.loanRecovery",
  "借入": "systemCategory.borrow",
  "借入借出": "systemCategory.borrowLend",
  "金融保险": "systemCategory.financeInsurance",
  "津贴补贴": "systemCategory.allowancesSubsidies",
  "经营成本": "systemCategory.operatingCosts",
  "经营收入": "systemCategory.businessIncome",
  "酒吧咖啡": "systemCategory.barsCafes",
  "酒店旅游": "systemCategory.hotelsTravel",
  "居住住房": "systemCategory.housing",
  "聚餐请客": "systemCategory.diningTreats",
  "考试认证": "systemCategory.examsCertification",
  "课外班": "systemCategory.extracurricularClasses",
  "快递物流": "systemCategory.deliveryLogistics",
  "宽带": "systemCategory.broadband",
  "宽带电视": "systemCategory.broadbandTv",
  "礼金": "systemCategory.ceremonialGift",
  "理财分红": "systemCategory.wealthDividend",
  "理财亏损": "systemCategory.wealthLoss",
  "理财买入": "systemCategory.wealthBuy",
  "理财收益": "systemCategory.wealthProfit",
  "理财赎回": "systemCategory.wealthRedeem",
  "理财投资": "systemCategory.wealthInvestment",
  "利息": "systemCategory.interest",
  "利息支出": "systemCategory.interestExpense",
  "临时支出": "systemCategory.temporaryExpenses",
  "零食饮料": "systemCategory.snacksDrinks",
  "流量套餐": "systemCategory.dataPlans",
  "旅游": "systemCategory.travel",
  "买菜食材": "systemCategory.groceries",
  "买入失败": "systemCategory.buyFailed",
  "买入退回": "systemCategory.buyRefund",
  "美容美发": "systemCategory.beautyHair",
  "美妆护肤": "systemCategory.cosmeticsSkincare",
  "母婴亲子": "systemCategory.motherBaby",
  "奶粉尿裤": "systemCategory.formulaDiapers",
  "年终奖": "systemCategory.yearEndBonus",
  "培训课程": "systemCategory.trainingCourses",
  "朋友差旅费": "systemCategory.friendTravelAdvance",
  "朋友代付": "systemCategory.friendPaymentAdvance",
  "朋友代购费": "systemCategory.friendPurchaseAdvance",
  "朋友其他代付": "systemCategory.friendOtherAdvance",
  "朋友转入": "systemCategory.fromFriends",
  "其他代付": "systemCategory.otherAdvance",
  "其他收入": "systemCategory.otherIncome",
  "其他投资": "systemCategory.otherInvestment",
  "其他杂项支出": "systemCategory.otherMiscExpenses",
  "其他支出": "systemCategory.otherExpenses",
  "其他转账": "systemCategory.otherTransfers",
  "棋牌": "systemCategory.boardGames",
  "亲友代付": "systemCategory.relativesAdvance",
  "清洁用品": "systemCategory.cleaningSupplies",
  "请客": "systemCategory.treating",
  "燃气费": "systemCategory.gas",
  "人情开支": "systemCategory.socialExpenses",
  "人情往来": "systemCategory.giftsSocial",
  "日用百货": "systemCategory.dailyNecessities",
  "日用品": "systemCategory.dailyGoods",
  "软件会员": "systemCategory.softwareMemberships",
  "赡养公益": "systemCategory.supportCharity",
  "赡养老人": "systemCategory.elderlySupport",
  "商业服务": "systemCategory.businessServices",
  "设备工具": "systemCategory.equipmentTools",
  "社保补贴": "systemCategory.socialSecuritySubsidy",
  "摄影": "systemCategory.photography",
  "生活费": "systemCategory.livingExpenses",
  "生活服务": "systemCategory.lifeServices",
  "生育津贴": "systemCategory.maternityAllowance",
  "失业金": "systemCategory.unemploymentBenefits",
  "饰品配件": "systemCategory.accessories",
  "收回": "systemCategory.collect",
  "手机电脑": "systemCategory.phonesComputers",
  "手机话费": "systemCategory.phoneBills",
  "手续费": "systemCategory.serviceFees",
  "书本资料": "systemCategory.booksMaterials",
  "数码电器": "systemCategory.digitalAppliances",
  "数码家电": "systemCategory.digitalHomeAppliances",
  "数码配件": "systemCategory.digitalAccessories",
  "水费": "systemCategory.water",
  "水果": "systemCategory.fruit",
  "税费": "systemCategory.taxesFees",
  "探望慰问": "systemCategory.visitsCondolences",
  "提前还款": "systemCategory.earlyRepayment",
  "体检": "systemCategory.physicalExam",
  "停车费": "systemCategory.parking",
  "通讯网络": "systemCategory.communicationsInternet",
  "童装": "systemCategory.childrenClothing",
  "投资": "systemCategory.investment",
  "投资分红": "systemCategory.investmentDividend",
  "投资记录": "systemCategory.investmentRecords",
  "投资亏损": "systemCategory.investmentLoss",
  "投资收入": "systemCategory.investmentIncome",
  "投资收益": "systemCategory.investmentProfit",
  "退款": "systemCategory.refunds",
  "退款返现": "systemCategory.refundsCashback",
  "托育幼儿园": "systemCategory.nurseryKindergarten",
  "外卖": "systemCategory.foodDelivery",
  "玩具": "systemCategory.toys",
  "晚餐": "systemCategory.dinner",
  "往来款": "systemCategory.transaction",
  "维修配件": "systemCategory.repairParts",
  "维修维护": "systemCategory.repairsMaintenance",
  "未分类收入": "systemCategory.uncategorizedIncome",
  "未分类支出": "systemCategory.uncategorizedExpenses",
  "文化休闲": "systemCategory.cultureLeisure",
  "文具": "systemCategory.stationery",
  "午餐": "systemCategory.lunch",
  "物业费": "systemCategory.propertyFees",
  "物业杂费": "systemCategory.propertyMiscFees",
  "洗护美发": "systemCategory.hairCare",
  "现金分红": "systemCategory.cashDividend",
  "项目收入": "systemCategory.projectIncome",
  "信用借还": "systemCategory.creditBorrowing",
  "信用卡费用": "systemCategory.creditCardFees",
  "兴趣班": "systemCategory.hobbyClasses",
  "学费": "systemCategory.tuition",
  "牙科": "systemCategory.dental",
  "烟酒茶": "systemCategory.tobaccoAlcoholTea",
  "眼科": "systemCategory.eyeCare",
  "养老金": "systemCategory.pension",
  "药品": "systemCategory.medicine",
  "业务招待": "systemCategory.businessEntertainment",
  "医疗健康": "systemCategory.medicalHealth",
  "意外收入": "systemCategory.windfallIncome",
  "银行分期": "systemCategory.bankInstallment",
  "营业收入": "systemCategory.operatingRevenue",
  "佣金提成": "systemCategory.commissions",
  "游戏": "systemCategory.gaming",
  "娱乐休闲": "systemCategory.entertainmentLeisure",
  "云服务": "systemCategory.cloudServices",
  "运动户外": "systemCategory.sportsOutdoors",
  "在线课程": "systemCategory.onlineCourses",
  "早餐": "systemCategory.breakfast",
  "长途客运": "systemCategory.longDistanceBus",
  "账户存取": "systemCategory.accountDepositWithdrawal",
  "政府补助": "systemCategory.governmentSubsidies",
  "住房物业": "systemCategory.housingProperty",
  "住院": "systemCategory.hospitalization",
  "转账": "systemCategory.transfer",
  "装修": "systemCategory.homeRenovation",
  "资金账户": "systemCategory.fundAccount",
  "装修投入": "systemCategory.renovation",
  "子女育儿": "systemCategory.childcareParenting",
  "宗教香火": "systemCategory.religionOfferings",
  "租金收入": "systemCategory.rentalIncome",
};

export function isSystemCategoryName(name?: string | null): boolean {
  return !!name && Object.prototype.hasOwnProperty.call(SYSTEM_CATEGORY_LABEL_KEYS, name);
}

/**
 * Returns the localized display label for a system category name.
 * Falls back to the raw name for unknown (user-created) categories.
 */
export function systemCategoryLabel(name: string | null | undefined, t?: TFunc): string {
  const raw = String(name ?? "").trim();
  if (!raw) return "";
  const key = SYSTEM_CATEGORY_LABEL_KEYS[raw];
  if (!key) return raw;
  if (t) return t(key);
  // No t provided: use the zh-CN label (default display language)
  return translate("zh-CN", key);
}
