import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { FundCashFlowKind, FundSubtype, Prisma, TransactionType, IntervalUnit, RegularInvestStatus } from "@prisma/client";
import { recalcFundPositions } from "@/lib/fund/recalcPosition";
import { recalcAndSaveAccountBalance } from "@/lib/server/account-balance";
import { getFundConfirmDays, getFundArrivalDays, normalizeNonNegativeDays } from "@/lib/fund/confirmDays";
import { getFundFeeRate, getFundFeeRateByDate } from "@/lib/fund/feeRate";
import { normalizeFundDisplayName, resolveFundName } from "@/lib/fund/fundProfile";
import { createFundTransactionWithCashFlows } from "@/lib/fund/transactions";
import { getFundNavFromCacheOnly } from "@/lib/fund/navCache";
import { normalizeFundUnitsDecimals, roundFundUnits } from "@/lib/fund/unit-precision";
import { calculateConfirmedBuyUnits } from "@/lib/fund/refund-link";
import {
  REGULAR_INVEST_CATEGORY_NAME,
  regularInvestBuyNote,
  regularInvestFailureNote,
  regularInvestRefundNote,
} from "@/lib/fund/regular-invest-display";
import { addWorkdaysUtc, formatDateUtc, startOfDayUtc } from "@/lib/date-utils";
import { logger } from "@/lib/logger";
import { getHouseholdScope } from "@/lib/server/household-scope";
import { decodeScheduledTaskMemo, scheduledTaskTypeLabel } from "@/lib/scheduled-task";
import { revalidateAfterInvestChange, revalidateAfterTxChange } from "@/lib/server/revalidate";
import { calcNextScheduledRunDate as calcNextRunDate, skipWeekend } from "@/lib/scheduled-task-date";
import { executeNonFundScheduledTaskPlan, getScheduledTaskSourceFilter, isNonFundScheduledTask, type NonFundTaskType } from "@/lib/server/scheduled-task-executor";
import { resolveCategorySnapshot } from "@/lib/default-categories";
import { acquireScheduledTaskPlanLock } from "@/lib/server/scheduled-task-lock";
import { ENTRY_ORIGIN_SCHEDULED_TASK } from "@/lib/transaction-semantics";

const SCHEDULED_EXECUTE_TRANSACTION_OPTIONS = {
  maxWait: 10_000,
  timeout: 60_000,
};

export async function POST(req: NextRequest) {
  try {
    const { householdId } = await getHouseholdScope();

    const body = await req.json();
    const { planId, overrideDate, overrideAmount } = body;

    if (!planId) {
      return NextResponse.json({ ok: false, code: "PLAN_ID_REQUIRED", error: "缺少 planId" }, { status: 400 });
    }

    const plan = await prisma.regularInvestPlan.findUnique({
      where: { id: planId },
    });

    if (!plan) {
      return NextResponse.json({ ok: false, code: "PLAN_NOT_FOUND", error: "计划不存在" }, { status: 404 });
    }

    if (plan.householdId && plan.householdId !== householdId) {
      return NextResponse.json({ ok: false, code: "PLAN_NOT_IN_HOUSEHOLD", error: "计划不属于当前账簿" }, { status: 403 });
    }

    const scheduledTask = decodeScheduledTaskMemo(plan.memo);
    const isNonFundTask = isNonFundScheduledTask(scheduledTask.type);
    const canBackfillCompletedNonFundTask = isNonFundTask && plan.status === RegularInvestStatus.completed && plan.executedRuns === 0;

    // Status check: historical transfer/loan/insurance plans may have past end dates but still need records generated first.
    if (plan.status !== RegularInvestStatus.active && !canBackfillCompletedNonFundTask) {
      return NextResponse.json({
        ok: false,
        code: "PLAN_NOT_ACTIVE",
        error: `计划状态为 ${plan.status}，只有 active 状态才能执行`,
      }, { status: 400 });
    }

    // Fund regular invests execute on the current date; non-fund plans have historical records
    // generated by the executor from startDate to endDate/today.
    const now = new Date();
    if (!isNonFundTask && plan.endDate && plan.endDate < now) {
      // End date reached; automatically mark as completed
      await prisma.regularInvestPlan.update({
        where: { id: planId },
        data: { status: RegularInvestStatus.completed },
      });
      return NextResponse.json({ ok: false, code: "PLAN_ENDED", error: "计划已达到结束日期，自动标记为已完成" }, { status: 400 });
    }

    if (plan.totalRuns && plan.executedRuns >= plan.totalRuns) {
      // Execution count reached; automatically mark as completed
      await prisma.regularInvestPlan.update({
        where: { id: planId },
        data: { status: RegularInvestStatus.completed },
      });
      return NextResponse.json({ ok: false, code: "PLAN_EXECUTION_COMPLETED", error: "计划已达到执行次数，自动标记为已完成" }, { status: 400 });
    }

    if (isNonFundTask) {
      const parsedOverrideAmount = overrideAmount ? parseFloat(overrideAmount) : null;
      const result = await executeNonFundScheduledTaskPlan({
        householdId,
        plan,
        task: scheduledTask,
        overrideDate: overrideDate ? new Date(overrideDate) : null,
        overrideAmount: parsedOverrideAmount && Number.isFinite(parsedOverrideAmount) ? parsedOverrideAmount : null,
        now,
      });
      return NextResponse.json({
        ok: true,
        message: result.message,
        date: result.date,
        executedCount: result.generatedCount,
        executedRuns: result.executedRuns,
        completed: result.completed,
        stats: result.stats,
      });
    }

    const fundAcc = await prisma.account.findUnique({ where: { id: plan.accountId } });
    if (!fundAcc) {
      return NextResponse.json({ ok: false, code: "FUND_ACCOUNT_NOT_FOUND", error: "基金账户不存在" }, { status: 400 });
    }
    const fundUnitsDecimals = normalizeFundUnitsDecimals(fundAcc.fundUnitsDecimals);

    const cashAcc = plan.cashAccountId
      ? await prisma.account.findUnique({ where: { id: plan.cashAccountId }, select: { id: true, name: true, currency: true } })
      : null;

    const task = decodeScheduledTaskMemo(plan.memo);
    const runDateBase = overrideDate
      ? startOfDayUtc(new Date(overrideDate))
      : task.type === "fund_regular_invest"
        ? startOfDayUtc(new Date())
        : startOfDayUtc(new Date(plan.nextRunDate));
    const runDate = task.type === "fund_regular_invest" ? skipWeekend(runDateBase) : runDateBase;
    const amountNum = overrideAmount ? parseFloat(overrideAmount) : parseFloat(String(plan.amount));
    if (!Number.isFinite(amountNum) || amountNum <= 0) {
      return NextResponse.json({ ok: false, code: "INVALID_AMOUNT", error: "金额不正确" }, { status: 400 });
    }

    const usesBusinessDays = task.type === "fund_regular_invest";

    if (task.type !== "fund_regular_invest") {
      if (!cashAcc?.id) {
        return NextResponse.json({ ok: false, code: "CASH_ACCOUNT_MISSING", error: "计划缺少资金账户" }, { status: 400 });
      }

      const today = startOfDayUtc(now);
      const effectiveEndDate = plan.endDate && startOfDayUtc(plan.endDate) < today ? startOfDayUtc(plan.endDate) : today;
      const sourceFilter = getScheduledTaskSourceFilter(task.type as NonFundTaskType);
      const existingTxRecords = await prisma.txRecord.findMany({
        where: {
          householdId,
          regularInvestPlanId: planId,
          source: { in: sourceFilter },
          deletedAt: null,
        },
        select: { date: true },
      });
      const existingDates = new Set(existingTxRecords.map((record) => formatDateUtc(record.date)));
      const remainingRuns = plan.totalRuns ? Math.max(0, plan.totalRuns - plan.executedRuns) : Number.POSITIVE_INFINITY;
      const datesToProcess: Date[] = [];

      if (overrideDate) {
        const dateStr = formatDateUtc(runDate);
        if (!existingDates.has(dateStr) && remainingRuns > 0) datesToProcess.push(runDate);
      } else {
        let currentDate = startOfDayUtc(plan.nextRunDate);
        let guard = 0;
        while (currentDate <= effectiveEndDate && datesToProcess.length < remainingRuns) {
          const dateStr = formatDateUtc(currentDate);
          if (!existingDates.has(dateStr)) datesToProcess.push(currentDate);
          currentDate = calcNextRunDate(
            currentDate,
            plan.intervalUnit as IntervalUnit,
            plan.intervalValue,
            plan.executionDay,
            false,
            plan.secondaryExecutionDay,
          );
          guard++;
          if (guard > 1200) throw new Error("计划周期异常，已停止生成以避免无限循环");
        }
      }

      if (datesToProcess.length === 0) {
        return NextResponse.json({
          ok: true,
          message: "所有到期的计划记录已存在，无需重复生成",
          executedCount: 0,
          date: formatDateUtc(runDate),
          executedRuns: plan.executedRuns,
          completed: false,
        });
      }

      const insuranceProduct = task.type === "insurance_premium"
        ? await prisma.insuranceProduct.findFirst({
            where: { id: task.insuranceProductId || "", householdId },
          })
        : null;
      if (task.type === "insurance_premium" && !task.insuranceProductId) {
        return NextResponse.json({ ok: false, code: "INSURANCE_PRODUCT_MISSING", error: "计划缺少保险产品" }, { status: 400 });
      }
      if (task.type === "insurance_premium" && !insuranceProduct) {
        return NextResponse.json({ ok: false, code: "INSURANCE_PRODUCT_NOT_FOUND", error: "保险产品不存在" }, { status: 400 });
      }

      const finalLastRunDate = datesToProcess[datesToProcess.length - 1]!;
      const finalExecutedRuns = plan.executedRuns + datesToProcess.length;
      const nextRun = calcNextRunDate(
        finalLastRunDate,
        plan.intervalUnit as IntervalUnit,
        plan.intervalValue,
        plan.executionDay,
        false,
        plan.secondaryExecutionDay,
      );
      const willComplete = !!(
        (plan.totalRuns && finalExecutedRuns >= plan.totalRuns) ||
        (plan.endDate && startOfDayUtc(plan.endDate) < nextRun)
      );

      await prisma.$transaction(async (tx) => {
        for (const scheduledRunDate of datesToProcess) {
          if (task.type === "transfer" || task.type === "loan_repayment") {
            await tx.txRecord.create({
              data: {
                householdId,
                type: TransactionType.transfer,
                date: scheduledRunDate,
                accountId: cashAcc.id,
                accountName: cashAcc.name,
                toAccountId: fundAcc.id,
                toAccountName: fundAcc.name,
                amount: -amountNum,
                source: "scheduled_task",
                entryOrigin: ENTRY_ORIGIN_SCHEDULED_TASK,
                regularInvestPlanId: planId,
                note: task.type === "loan_repayment" ? "计划任务：还贷款" : "计划任务：转账",
              },
            });
          } else if (task.type === "insurance_premium" && insuranceProduct) {
            await tx.txRecord.create({
              data: {
                householdId,
                type: TransactionType.investment,
                date: scheduledRunDate,
                accountId: cashAcc.id,
                accountName: cashAcc.name,
                toAccountId: insuranceProduct.accountId,
                toAccountName: fundAcc.name,
                amount: -amountNum,
                fundName: insuranceProduct.name,
                fundSubtype: "buy",
                insuranceAction: "premium",
                insuranceProductName: insuranceProduct.name,
                source: "insurance",
                entryOrigin: ENTRY_ORIGIN_SCHEDULED_TASK,
                insuranceProductId: insuranceProduct.id,
                regularInvestPlanId: planId,
                note: `计划任务：保险缴费：${insuranceProduct.name}`,
              },
            });
          }
        }

        await tx.regularInvestPlan.update({
          where: { id: planId },
          data: {
            lastRunDate: finalLastRunDate,
            nextRunDate: nextRun,
            executedRuns: finalExecutedRuns,
            status: willComplete ? RegularInvestStatus.completed : RegularInvestStatus.active,
          },
        });
      }, SCHEDULED_EXECUTE_TRANSACTION_OPTIONS);

      await recalcAndSaveAccountBalance(cashAcc.id).catch(logger.catchLog("操作失败", "route.ts"));
      await recalcAndSaveAccountBalance(fundAcc.id).catch(logger.catchLog("操作失败", "route.ts"));
      if (task.type === "insurance_premium") revalidateAfterInvestChange();
      else revalidateAfterTxChange();

      return NextResponse.json({
        ok: true,
        message: `已执行${scheduledTaskTypeLabel(task.type)}，生成 ${datesToProcess.length} 条交易明细，金额 ${amountNum.toFixed(2)}，累计第 ${finalExecutedRuns} 次`,
        date: formatDateUtc(finalLastRunDate),
        executedCount: datesToProcess.length,
        executedRuns: finalExecutedRuns,
        completed: willComplete,
      });
    }

    const newExecutedRuns = plan.executedRuns + 1;
    const nextRun = calcNextRunDate(
      runDate,
      plan.intervalUnit as IntervalUnit,
      plan.intervalValue,
      plan.executionDay,
      usesBusinessDays,
      plan.secondaryExecutionDay,
    );

    // Determine whether the completion condition is met after execution
    const willComplete =
      (plan.totalRuns && newExecutedRuns >= plan.totalRuns) ||
      (plan.endDate && plan.endDate < nextRun);

    // Precompute outside the transaction so NAV, fee-rate, and category lookups do not count toward the Prisma interactive transaction.
    const runDateStr = formatDateUtc(runDate);
    const confirmDays = normalizeNonNegativeDays(plan.confirmDays ?? await getFundConfirmDays(plan.accountId, plan.fundCode), 0);
    let confirmDateStr = addWorkdaysUtc(runDateStr, confirmDays);
    if (confirmDateStr < runDateStr) {
      logger.warn(`confirmDate ${confirmDateStr} < runDate ${runDateStr}, confirmDays=${confirmDays}, planId=${planId}`, "execute");
      confirmDateStr = runDateStr;
    }
    const confirmDate = new Date(Date.UTC(
      parseInt(confirmDateStr.slice(0, 4)),
      parseInt(confirmDateStr.slice(5, 7)) - 1,
      parseInt(confirmDateStr.slice(8, 10))
    ));
    const arrivalDays = normalizeNonNegativeDays(plan.arrivalDays ?? await getFundArrivalDays(plan.accountId, plan.fundCode), 2);
    const arrivalDateStr = arrivalDays > 0 ? addWorkdaysUtc(confirmDateStr, arrivalDays) : confirmDateStr;
    const arrivalDate = new Date(Date.UTC(
      parseInt(arrivalDateStr.slice(0, 4)),
      parseInt(arrivalDateStr.slice(5, 7)) - 1,
      parseInt(arrivalDateStr.slice(8, 10))
    ));
    const foundNav = await getFundNavFromCacheOnly(plan.fundCode, confirmDate);
    const sgzt = foundNav?.sgzt ?? "";
    let feeRateRaw = await getFundFeeRateByDate(plan.accountId, plan.fundCode, runDate, "buy");
    if (feeRateRaw === 0) {
      feeRateRaw = await getFundFeeRate(plan.accountId, plan.fundCode, "buy");
    }
    const feeRate = feeRateRaw / 100;
    const feeAmountNumber = feeRate > 0 ? amountNum * feeRate : 0;
    const feeAmount = feeAmountNumber > 0 ? new Prisma.Decimal(feeAmountNumber) : null;
    let fundNav: number | null = null;
    let fundUnits: number | null = null;
    const foundNavInfo = await getFundNavFromCacheOnly(plan.fundCode, confirmDate);
    if (foundNavInfo && foundNavInfo.nav > 0) {
      fundNav = foundNavInfo.nav;
      fundUnits = calculateConfirmedBuyUnits({
        grossAmount: amountNum,
        refundAmount: 0,
        fee: feeAmountNumber,
        nav: foundNavInfo.nav,
        roundUnits: (value) => roundFundUnits(value, fundUnitsDecimals),
      });
    }
    const category = await resolveCategorySnapshot(prisma, householdId, {
      categoryName: REGULAR_INVEST_CATEGORY_NAME,
      type: "investment",
    });
    const fundDisplayName = await resolveFundName(plan.fundCode, { householdId })
      ?? normalizeFundDisplayName(plan.fundCode, plan.fundName)
      ?? plan.fundCode;

    const result = await prisma.$transaction(async (tx) => {
      await acquireScheduledTaskPlanLock(tx, planId);

      const existingForRunDate = await tx.fundTransaction.findFirst({
        where: {
          householdId,
          regularInvestPlanId: planId,
          source: "regular_invest",
          deletedAt: null,
          applyDate: runDate,
        },
        select: { id: true },
      });
      if (existingForRunDate) return { skippedDuplicate: true, buyFailed: false };

      // Suspended purchase: create two offsetting records that sum to 0
      // Record 1: regular invest (suspended) - from cash account to fund account, amount -100
      // Record 2: regular invest (refund) - from fund account to cash account, amount -100
      // Cash account view: record 1 is an outflow, record 2 is an inflow, offsetting to 0
      // Fund account view: both buy_failed records are skipped in position calculation
      if (sgzt === "暂停申购") {
        await createFundTransactionWithCashFlows(tx, {
          householdId,
          fundAccountId: fundAcc.id,
          cashAccountId: cashAcc?.id ?? null,
          fundCode: plan.fundCode,
          fundName: fundDisplayName,
          fundProductType: plan.fundProductType || fundAcc.investProductType,
          fundSubtype: FundSubtype.buy_failed,
          source: "regular_invest",
          entryOrigin: ENTRY_ORIGIN_SCHEDULED_TASK,
          applyDate: runDate,
          confirmDate,
          arrivalDate,
          grossAmount: amountNum,
          refundAmount: amountNum,
          fee: null,
          nav: null,
          units: null,
          regularInvestPlanId: planId,
          note: regularInvestFailureNote(plan.fundCode, fundDisplayName, runDate),
          cashFlows: cashAcc ? [
            {
              kind: FundCashFlowKind.buy_out,
              date: runDate,
              accountId: cashAcc.id,
              accountName: cashAcc.name,
              amount: -amountNum,
              currency: cashAcc.currency ?? fundAcc.currency ?? "CNY",
              source: "regular_invest",
              regularInvestPlanId: planId,
              note: regularInvestFailureNote(plan.fundCode, fundDisplayName, runDate),
            },
            {
              kind: FundCashFlowKind.refund_in,
              date: arrivalDate,
              accountId: cashAcc.id,
              accountName: cashAcc.name,
              amount: amountNum,
              currency: cashAcc.currency ?? fundAcc.currency ?? "CNY",
              source: "regular_invest_refund",
              regularInvestPlanId: planId,
              note: regularInvestRefundNote(
                plan.fundCode,
                fundDisplayName,
                amountNum,
                runDate,
                cashAcc.currency ?? fundAcc.currency ?? "CNY",
              ),
            },
          ] : [],
        });

        // Update the plan (a suspended purchase still counts as one execution)
        await tx.regularInvestPlan.update({
          where: { id: planId },
          data: {
            lastRunDate: runDate,
            nextRunDate: skipWeekend(nextRun),
            executedRuns: newExecutedRuns,
            status: willComplete ? RegularInvestStatus.completed : RegularInvestStatus.active,
          },
        });
        return { buyFailed: true };
      }

      await createFundTransactionWithCashFlows(tx, {
        householdId,
        fundAccountId: fundAcc.id,
        cashAccountId: cashAcc?.id ?? null,
        fundCode: plan.fundCode,
        fundName: fundDisplayName,
        fundProductType: plan.fundProductType || fundAcc.investProductType,
        fundSubtype: FundSubtype.buy,
        source: "regular_invest",
        entryOrigin: ENTRY_ORIGIN_SCHEDULED_TASK,
        applyDate: runDate,
        confirmDate,
        arrivalDate,
        grossAmount: amountNum,
        fee: feeAmount,
        nav: fundNav,
        units: fundUnits,
        regularInvestPlanId: planId,
        note: regularInvestBuyNote(plan.fundCode, fundDisplayName),
        cashFlows: cashAcc ? [{
          kind: FundCashFlowKind.buy_out,
          date: runDate,
          accountId: cashAcc.id,
          accountName: cashAcc.name,
          amount: -amountNum,
          currency: cashAcc.currency ?? fundAcc.currency ?? "CNY",
          source: "regular_invest",
          categoryId: category?.id ?? null,
          categoryName: category?.name ?? REGULAR_INVEST_CATEGORY_NAME,
          regularInvestPlanId: planId,
          note: regularInvestBuyNote(plan.fundCode, fundDisplayName),
        }] : [],
      });

      // Update the regular invest plan
      await tx.regularInvestPlan.update({
        where: { id: planId },
        data: {
          lastRunDate: runDate,
          nextRunDate: skipWeekend(nextRun),
          executedRuns: newExecutedRuns,
          status: willComplete ? RegularInvestStatus.completed : RegularInvestStatus.active,
        },
      });

      return { buyFailed: false };
    }, SCHEDULED_EXECUTE_TRANSACTION_OPTIONS);

    if (result.skippedDuplicate) {
      return NextResponse.json({
        ok: true,
        message: "该执行日期的交易明细已存在，无需重复生成",
        date: formatDateUtc(runDate),
        executedRuns: plan.executedRuns,
        completed: false,
        executedCount: 0,
      });
    }

    await recalcFundPositions(fundAcc.id, [plan.fundCode]).catch(logger.catchLog("操作失败", "route.ts"));
    // Refresh involved account balances (cash and investment accounts)
    if (cashAcc?.id) await recalcAndSaveAccountBalance(cashAcc.id).catch(logger.catchLog("操作失败", "route.ts"));
    await recalcAndSaveAccountBalance(fundAcc.id).catch(logger.catchLog("操作失败", "route.ts"));
    revalidateAfterInvestChange();

    // Client-side handles page refresh via dispatchFinanceDataChanged (mmh:finance:changed)

    if (result.buyFailed) {
      return NextResponse.json({
        ok: true,
        buyFailed: true,
        message: `基金暂停申购 ${plan.fundCode}，已生成两条对冲记录，金额 ${amountNum.toFixed(2)}，第 ${newExecutedRuns} 次`,
        date: formatDateUtc(runDate),
        executedRuns: newExecutedRuns,
        completed: willComplete,
      });
    }

    return NextResponse.json({
      ok: true,
      message: `已执行基金定投 ${plan.fundCode}，金额 ${amountNum.toFixed(2)}，第 ${newExecutedRuns} 次`,
      date: formatDateUtc(runDate),
      executedRuns: newExecutedRuns,
      completed: willComplete,
    });
  } catch (e) {
    return NextResponse.json({ ok: false, code: "EXECUTE_FAILED", error: e instanceof Error ? e.message : "执行失败" }, { status: 500 });
  }
}
